on:
    push:
        branches:
            -   main
jobs:
    ci:
        runs-on: ubuntu-20.04
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/cache@v2
                with:
                    path: node_modules
                    key: ${{ hashFiles('package.json') }}
            -   run: yarn
            -   run: yarn build
